### ISSUE TITLE
Error while downloading 2019 14.28.30040

### ISSUE THREAD

**Issue by S0ULL355** [ChxseH/Redist-Installer#1]
"{C874FB5A-1C85-460A-A4A9-CBCC3FAE7880}v14.29.30037\packages\vcRuntimeMinimum_amd64\ is missing" along with "vc_runtimeminimum_x64.msi" already tried to use vc_redist_x64 and that gives me the same problem aswell as uninstall and reinstall.

**Comment by ChxseH** [comment]
What version of Windows are you on? Please screenshot `winver` and post back here.

**Comment by S0ULL355** [comment]
![image](https://user-images.githubusercontent.com/48848185/126872146-f473c2c0-e42a-4d0d-aea4-02d4d86a54f2.png)
latest version as Windows 11 can be

**Comment by ChxseH** [comment]
Try manually installing things from your game(s) `redist` folder.

**Comment by S0ULL355** [comment]
VC_redist.x86 says this: 
![image](https://user-images.githubusercontent.com/48848185/126872745-21c35ffd-0491-4774-8112-b1b692b5c101.png)

**Comment by S0ULL355** [comment]
Update on the last comment: Did what it said but (in my case, I'm trying to get IW6x or Ghosts to work) the game still black screens.

**Comment by ChxseH** [comment]
Not an issue with the script itself, closing the issue as it pertains to your system in particular.

![img](https://i.imgur.com/cWqWbj1.png)
